export const axiosTypes = {
    LOGIN:'/Auth/Login',
    RECOVER_PASSWORD:'/Auth/RecoveryPassword',
    VALIDATE_COLLABORATOR:'/Auth/ValidateCollaborator',
    CHANGE_COLLABORATOR_PASSWORD:'/Auth/ChangeCollaboratorPassword',
    REFRESH_TOKEN:'/Auth/RefreshToken',
    GET_CODE:'/DynamicQr/Code/',
    VALIDATE_CODE: '/DynamicQr/Validate',
    CREATE_ACCESSLOCATION: '/AccessLocation/Create',
    GET_ACTIVES_ACCESSLOCATIONS:'/AccessLocation/Actives',
    SAVE_EXPO_TOKEN:'/Notifications/ExpoToken',
    GET_NOTIFICATIONS:'/Notifications/Collaborator',
    GET_BADGE_NOTIFY:'/Notifications/Badge',
    READ_NOTIFICATIONS:'/Notifications/Read',
    LOGOUT: '/Auth/Logout',
    CHANGE_EXPIRED_PASSWORD: '/Auth/ConfirmRecoveryPasswordCollaborator',
    ACCESS_LOG_COLLABORATOR:'/AccessLog/Collaborator',
    USER_PREFERENCES: '/UserConfiguration/preferences/',
    UPDATE_USER_PREFERENCES: '/UserConfiguration/Preferences',
    DELETE_PROFILE: '/DeletionRequests/Create/',
    GET_COLOR_DAY: '/SecurityConfiguration/GetTodayColor',
    GET_REGEX_PASSWORD: '/SecurityConfiguration/GetPasswordRegex',
    GET_PASSWORD_CONFIG:'/SecurityConfiguration/GetPasswordConfiguration',
    GET_GENERAL_CONFIG:'/GeneralConfiguration/App',
    GET_COMMUNICATIONS: '/Communications/App',
    GET_INFO_CREDENTIALS:'/UserConfiguration/credentials/',
    UPDATE_INFO_CREDENTIALS:'/UserConfiguration/Credentials'
}